services:
  esphome:
    image: ghcr.io/esphome/esphome:stable
    ports:
      - "6052:6052"
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    volumes:
      - ./config:/config
    stdin_open: true
    tty: true
    restart: "no"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock