substitutions:
  name: "esp32-bluetooth-proxy-1"
  friendly_name: ESP32 - Bluetooth Proxy - 1 (Wardrobe)
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret esp32_bluetooth_proxy_1_api_encryption_key
bluetooth_proxy:
  active: true
  cache_services: true
# logger:
#   level: VERBOSE
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
