esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret konnected_e2481d_api_encryption_key
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
substitutions:
  name: konnected-e2481d
  friendly_name: Konnected - Alarm Panel
  warning_beep_pin: $zone6
  warning_beep_pause_time: 200ms
# packages:
#   konnected.alarm-panel-esp8266: github://konnected-io/konnected-esphome/alarm-panel-esp8266.yaml@master
# See https://github.com/konnected-io/konnected-esphome/blob/master/alarm-panel-esp8266.yaml
# https://support.konnected.io/esphome-customize-buzzers-and-outputs-on-konnected-alarm-panels$0
packages:
  remote_package:
    url: https://github.com/konnected-io/konnected-esphome
    ref: master
    refresh: 5min
    files:
      - packages/alarm-panel-esp8266-base.yaml
      - packages/alarm-panel/zone1.yaml
      - packages/alarm-panel/zone2.yaml
      - packages/alarm-panel/zone3.yaml
      - packages/alarm-panel/zone4.yaml
      - packages/alarm-panel/zone5.yaml
      # - packages/alarm-panel/zone6.yaml
      # - packages/alarm-panel/alarm.yaml
      - packages/wifi.yaml
      - packages/mdns.yaml
      - packages/status-led.yaml
      - packages/warning-beep.yaml
switch:
  - id: siren
    name: Siren
    pin:
      number: $alarm
      allow_other_uses: false
    platform: gpio
    icon: mdi:bullhorn
web_server:
logger:
  level: VERBOSE
  logs:
    ledc.output: INFO
    sensor: INFO
    json: INFO
    api: DEBUG
    wifi: DEBUG
    wifi_esp8266: DEBUG
ota:
